name: 构建并上传小程序代码

on:
  push:
    branches: [main]
    paths: [miniprogram/**]
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          repository: misaka-1314/Chaoxing-MiniProgram

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 写入私钥和默认配置文件
        run: |
          echo "${{ secrets.KEY }}" > ./private.${{ secrets.APPID }}.key
          wget -O ./utils/config.js https://raw.githubusercontent.com/misaka-1314/Chaoxing-MiniProgram/refs/heads/main/resource/config.js
        working-directory: miniprogram

      - name: 安装依赖
        run: |
          npm install --omit=dev --no-audit
          npm install -g miniprogram-ci
        working-directory: miniprogram

      - name: 执行小程序编译上传
        run: |
          miniprogram-ci upload --pp ./ --pkp ./private.${{ secrets.APPID }}.key --appid ${{ secrets.APPID }} --enable-es6 true --robot 30 --upload-version misaka-1314 --upload-description "自动上传 By GitHub Actions，开源仓库：Misaka-1314/Chaoxing-MiniProgram"
        working-directory: miniprogram
