name: 构建 Web 镜像

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    runs-on: ubuntu-24.04

    steps:
      - name: 签出代码
        uses: actions/checkout@v4

      - name: 安装 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 安装 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录腾讯云容器镜像服务
        uses: docker/login-action@v3
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_REGISTRY_USERNAME }}
          password: ${{ secrets.TENCENT_REGISTRY_PASSWORD }}

      - name: 登录 GitHub 容器镜像服务
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: misaka-org
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 文件目录结构
        run: tree -a -L 2

      - name: 构建镜像
        uses: docker/build-push-action@v6
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: |
            ccr.ccs.tencentyun.com/misaka-public/chaoxing:web
          labels: |
            image.source=御坂学习
          platforms: linux/amd64
